const defaultLang = 'en';
const langs = ['en', 'sv', 'no', 'da', 'de', 'fi'] as const;

export function getLangs() {
  return [...langs] as string[];
}

export function getTranslation(lang: Lang) {
  if (lang === defaultLang) {
    return (key: Translation) => key;
  }
  return (key: Translation) => translations[key][lang];
}

export type Lang = (typeof langs)[number];
export type Translation = keyof typeof translations;

const translations = {
  // --- General ---
  'An online puzzle for you and your friends!': {
    sv: 'Ett online pussel för dig och dina vänner!',
    no: 'Et online puslespill for deg og vennene dine!',
    da: 'Et online puslespil for dig og dine venner!',
    de: 'Ein Online-Puzzle für dich und deine Freunde!',
    fi: 'Verkkopulmapeli sinulle ja ystävillesi!',
  },
  'A free and open-source online puzzle where friends and family can help each other and solve fun puzzles together!':
    {
      sv: 'Ett gratis och open-source online pussel där vänner och familj kan hjälpas åt och lösa roliga pussel ihop!',
      no: 'Et gratis og open-source online puslespill der venner og familie kan hjelpe hverandre og løse morsomme puslespill sammen!',
      da: 'Et gratis og open-source online puslespil, hvor venner og familie kan hjælpe hinanden og løse sjove puslespil sammen!',
      de: 'Ein kostenloses und Open-Source-Online-Puzzle, bei dem Freunde und Familie sich gegenseitig helfen und zusammen lustige Puzzles lösen können!',
      fi: 'Ilmainen ja avoimen lähdekoodin verkkopulmapeli, jossa ystävät ja perhe voivat auttaa toisiaan ja ratkaista hauskat pulmat yhdessä!',
    },
  'puzzle, online, friends, family, social, fun, collaboration, free, open source': {
    sv: 'pussel, online, vänner, familj, socialt, kul, samarbete, gratis, öppen källkod',
    no: 'puslespill, online, venner, familie, sosialt, moro, samarbeid, gratis, åpen kildekode',
    da: 'puslespil, online, venner, familie, socialt, sjovt, samarbejde, gratis, åben kildekode',
    de: 'Puzzle, Online, Freunde, Familie, sozial, Spaß, Zusammenarbeit, kostenlos, Open Source',
    fi: 'pulmapeli, verkossa, ystävät, perhe, sosiaalinen, hauska, yhteistyö, ilmainen, avoimen lähdekoodin',
  },
  'You have no ongoing puzzles': {
    sv: 'Du har inga påbörjade pussel',
    no: 'Du har ingen påbegynte puslespill',
    da: 'Du har ingen igangværende puslespil',
    de: 'Du hast keine laufenden Puzzles',
    fi: 'Sinulla ei ole käynnissä olevia pulmia',
  },
  'When you have started a puzzle it will show up here so that you can finish it later.': {
    sv: 'När du har påbörjat ett pussel visas det här så att du kan slutföra det senare.',
    no: 'Når du har startet et puslespill, vises det her slik at du kan fullføre det senere.',
    da: 'Når du har startet et puslespil, vises det her, så du kan fuldføre det senere.',
    de: 'Wenn Sie ein Puzzle gestartet haben, wird es hier angezeigt, damit Sie es später fertigstellen können.',
    fi: 'Kun olet aloittanut pulman, se näkyy täällä, jotta voit viimeistellä sen myöhemmin.',
  },
  'Select pieces and drag and rotate them to solve the puzzle. Invite your friends to help you!': {
    sv: 'Välj bitar och dra och rotera dem för att lösa pusslet. Bjud in dina vänner för att hjälpa dig!',
    no: 'Velg biter og dra og roter dem for å løse puslespillet. Inviter vennene dine til å hjelpe deg!',
    da: 'Vælg brikker og træk og roter dem for at løse puslespillet. Inviter dine venner til at hjælpe dig!',
    de: 'Wählen Sie Teile aus und ziehen und drehen Sie sie, um das Puzzle zu lösen. Lade deine Freunde ein, dir zu helfen!',
    fi: 'Valitse palat ja vedä ja pyöritä niitä ratkaistaksesi pulman. Kutsu ystäväsi auttamaan sinua!',
  },

  // --- General ---

  // --- Room ---
  'Join a room': {
    sv: 'Gå med i ett rum',
    no: 'Bli med i et rom',
    da: 'Bliv med i et rum',
    de: 'Treten Sie einem Raum bei',
    fi: 'Liity huoneeseen',
  },
  'Change room': {
    sv: 'Byt rum',
    no: 'Bytt rom',
    da: 'Skift rum',
    de: 'Raum wechseln',
    fi: 'Vaihda huonetta',
  },
  'Enter room code': {
    sv: 'Ange rumskod',
    no: 'Skriv inn romkode',
    da: 'Indtast rumkode',
    de: 'Geben Sie den Raumcode ein',
    fi: 'Anna huonekoodi',
  },
  'In Room': {
    sv: 'I rum',
    no: 'I rom',
    da: 'I rum',
    de: 'Im Raum',
    fi: 'Huoneessa',
  },
  // --- Room ---

  // --- Other ---
  'Upload image': {
    sv: 'Välj en egen bild',
    no: 'Last opp et bilde',
    da: 'Upload et billede',
    de: 'Lade ein Bild hoch',
    fi: 'Lataa kuva',
  },
  'Coming soon': {
    sv: 'Kommer snart',
    no: 'Kommer snart',
    da: 'Kommer snart',
    de: 'Kommt bald',
    fi: 'Tulossa pian',
  },
  'Invite friends': {
    sv: 'Bjud in vänner',
    no: 'Inviter venner',
    da: 'Inviter venner',
    de: 'Freunde einladen',
    fi: 'Kutsu ystäviä',
  },
  'Link copied!': {
    sv: 'Länk kopierad!',
    no: 'Lenke kopiert!',
    da: 'Link kopieret!',
    de: 'Link kopiert!',
    fi: 'Linkki kopioitu!',
  },
  'Room code': {
    sv: 'Rumskod',
    no: 'Romkode',
    da: 'Rumkode',
    de: 'Raumcode',
    fi: 'Huonekoodi',
  },
  'Copy room code': {
    sv: 'Kopiera rumskod',
    no: 'Kopier romkode',
    da: 'Kopier rumkode',
    de: 'Raumcode kopieren',
    fi: 'Kopioi huonekoodi',
  },
  'Copied!': {
    sv: 'Kopierad!',
    no: 'Kopiert!',
    da: 'Kopieret!',
    de: 'Kopiert!',
    fi: 'Kopioitu!',
  },
  'Share link': {
    sv: 'Dela länk',
    no: 'Del lenke',
    da: 'Del link',
    de: 'Link teilen',
    fi: 'Jaa linkki',
  },
  Close: {
    sv: 'Stäng',
    no: 'Lukk',
    da: 'Luk',
    de: 'Schließen',
    fi: 'Sulje',
  },
  Settings: {
    sv: 'Inställningar',
    no: 'Innstillinger',
    da: 'Indstillinger',
    de: 'Einstellungen',
    fi: 'Asetukset',
  },
  'Rotation speed': {
    sv: 'Rotationshastighet',
    no: 'Rotasjonshastighet',
    da: 'Rotationshastighed',
    de: 'Rotationsgeschwindigkeit',
    fi: 'Pyörimisnopeus',
  },
  'Key bindings': {
    sv: 'Tangentbindningar',
    no: 'Tastaturbindinger',
    da: 'Tastebindinger',
    de: 'Tastenbelegung',
    fi: 'Näppäinsidokset',
  },
  'Rotate left': {
    sv: 'Rotera vänster',
    no: 'Roter venstre',
    da: 'Roter venstre',
    de: 'Nach links drehen',
    fi: 'Kierrä vasemmalle',
  },
  'Rotate right': {
    sv: 'Rotera höger',
    no: 'Roter høyre',
    da: 'Roter højre',
    de: 'Nach rechts drehen',
    fi: 'Kierrä oikealle',
  },
  'Stack pieces': {
    sv: 'Stapla bitar',
    no: 'Stable brikker',
    da: 'Stak brikker',
    de: 'Teile stapeln',
    fi: 'Pinoa palat',
  },
  'Explode pieces': {
    sv: 'Sprid bitar',
    no: 'Spre brikker',
    da: 'Spred brikker',
    de: 'Teile verteilen',
    fi: 'Levitä palat',
  },
  'Select multiple': {
    sv: 'Markera fler',
    no: 'Velg flere',
    da: 'Vælg flere',
    de: 'Mehrere auswählen',
    fi: 'Valitse useita',
  },
  'Reconnect pieces': {
    sv: 'Koppla om bitar',
    no: 'Koble til brikker på nytt',
    da: 'Tilslut brikker igen',
    de: 'Teile neu verbinden',
    fi: 'Yhdistä palat uudelleen',
  },
  'Zoom in on the puzzle': {
    sv: 'Zooma in på pusslet',
    no: 'Zoom inn på puslespillet',
    da: 'Zoom ind på puslespillet',
    de: 'Puzzle vergrößern',
    fi: 'Lähennä pulmaa',
  },
  'Zoom out on the puzzle': {
    sv: 'Zooma ut på pusslet',
    no: 'Zoom ut på puslespillet',
    da: 'Zoom ud på puslespillet',
    de: 'Puzzle verkleinern',
    fi: 'Loitonna pulmasta',
  },
  'Rotate selected pieces clockwise': {
    sv: 'Rotera markerade bitar medurs',
    no: 'Roter valgte brikker med klokken',
    da: 'Roter markerede brikker med uret',
    de: 'Ausgewählte Teile im Uhrzeigersinn drehen',
    fi: 'Kierrä valittuja paloja myötäpäivään',
  },
  'Rotate selected pieces counter-clockwise': {
    sv: 'Rotera markerade bitar moturs',
    no: 'Roter valgte brikker mot klokken',
    da: 'Roter markerede brikker mod uret',
    de: 'Ausgewählte Teile gegen den Uhrzeigersinn drehen',
    fi: 'Kierrä valittuja paloja vastapäivään',
  },
  'Stack all selected pieces': {
    sv: 'Stapla alla markerade bitar',
    no: 'Stable alle valgte brikker',
    da: 'Stak alle markerede brikker',
    de: 'Alle ausgewählten Teile stapeln',
    fi: 'Pinoa kaikki valitut palat',
  },
  'Spread out selected pieces': {
    sv: 'Sprid ut markerade bitar',
    no: 'Spre ut valgte brikker',
    da: 'Spred markerede brikker',
    de: 'Ausgewählte Teile verteilen',
    fi: 'Levitä valitut palat',
  },
  'Deselect all pieces': {
    sv: 'Avmarkera alla bitar',
    no: 'Fjern markeringen av alle brikker',
    da: 'Fravælg alle brikker',
    de: 'Alle Teile abwählen',
    fi: 'Poista kaikkien palojen valinta',
  },
  'Reconnect selected pieces': {
    sv: 'Koppla om markerade bitar',
    no: 'Koble til valgte brikker på nytt',
    da: 'Tilslut markerede brikker igen',
    de: 'Ausgewählte Teile neu verbinden',
    fi: 'Yhdistä valitut palat uudelleen',
  },
  'Invert zoom': {
    sv: 'Invertera zoom',
    no: 'Inverter zoom',
    da: 'Inverter zoom',
    de: 'Zoom umkehren',
    fi: 'Käännä zoomaus',
  },
  'Hide puzzle action buttons': {
    sv: 'Dölj pusselknappar',
    no: 'Skjul pusleknapper',
    da: 'Skjul puslespilknapper',
    de: 'Puzzle-Aktionsschaltflächen ausblenden',
    fi: 'Piilota pulman toimintopainikkeet',
  },
  'Show FPS counter': {
    sv: 'Visa FPS räknare',
    no: 'Vis FPS-teller',
    da: 'Vis FPS-tæller',
    de: 'FPS-Zähler anzeigen',
    fi: 'Näytä FPS-laskuri',
  },
  'Background color': {
    sv: 'Bakgrundsfärg',
    no: 'Bakgrunnsfarge',
    da: 'Baggrundsfarve',
    de: 'Hintergrundfarbe',
    fi: 'Taustaväri',
  },
  'Press key': {
    sv: 'Tryck på tangent',
    no: 'Trykk på tast',
    da: 'Tryk på tast',
    de: 'Taste drücken',
    fi: 'Paina näppäintä',
  },
  Space: {
    sv: 'Mellanslag',
    no: 'Mellomrom',
    da: 'Mellemrum',
    de: 'Leertaste',
    fi: 'Välilyönti',
  },
  Dark: {
    sv: 'Mörk',
    no: 'Mørk',
    da: 'Mørk',
    de: 'Dunkel',
    fi: 'Tumma',
  },
  Medium: {
    sv: 'Mellan',
    no: 'Middels',
    da: 'Medium',
    de: 'Mittel',
    fi: 'Keskitaso',
  },
  Light: {
    sv: 'Ljus',
    no: 'Lys',
    da: 'Lys',
    de: 'Hell',
    fi: 'Vaalea',
  },
  Size: {
    sv: 'Storlek',
    no: 'Størrelse',
    da: 'Størrelse',
    de: 'Größe',
    fi: 'Koko',
  },
  'Select size': {
    sv: 'Välj storlek',
    no: 'Velg størrelse',
    da: 'Vælg størrelse',
    de: 'Größe auswählen',
    fi: 'Valitse koko',
  },
  // --- Other ---

  // --- Delete ---
  'Delete puzzle': {
    sv: 'Ta bort pussel',
    no: 'Slett puslespill',
    da: 'Slet puslespil',
    de: 'Lösche Puzzle',
    fi: 'Poista pulma',
  },
  'Are you sure?': {
    sv: 'Är du säker?',
    no: 'Er du sikker?',
    da: 'Er du sikker?',
    de: 'Bist du sicher?',
    fi: 'Oletko varma?',
  },
  'Progress will be lost': {
    sv: 'Framsteg kommer att förloras',
    no: 'Fremgang vil gå tapt',
    da: 'Fremskridt vil gå tabt',
    de: 'Fortschritt geht verloren',
    fi: 'Edistyminen menetetään',
  },
  Yes: {
    sv: 'Ja',
    no: 'Ja',
    da: 'Ja',
    de: 'Ja',
    fi: 'Kyllä',
  },
  No: {
    sv: 'Nej',
    no: 'Nei',
    da: 'Nej',
    de: 'Nein',
    fi: 'Ei',
  },
  // --- Delete ---

  // --- Puzzle ---
  'New puzzle': {
    sv: 'Nytt pussel',
    no: 'Nytt puslespill',
    da: 'Nyt puslespil',
    de: 'Neues Puzzle',
    fi: 'Uusi pulma',
  },
  'Begin puzzle': {
    sv: 'Börja pussla',
    no: 'Begynn å pusle',
    da: 'Begynd at pusle',
    de: 'Puzzle beginnen',
    fi: 'Aloita pulma',
  },
  'Continue puzzle': {
    sv: 'Fortsätt pussla',
    no: 'Fortsett puslespill',
    da: 'Fortsæt med at pusle',
    de: 'Puzzle fortsetzen',
    fi: 'Jatka pulmaa',
  },
  'Preparing your puzzle': {
    sv: 'Förbereder ditt pussel',
    no: 'Forbereder puslespillet ditt',
    da: 'Forbereder dit puslespil',
    de: 'Bereite dein Puzzle vor',
    fi: 'Valmistellaan pulmaasi',
  },
  // --- Puzzle ---

  // --- Categories ---
  Christmas: {
    sv: 'Jul',
    no: 'Jul',
    da: 'Jul',
    de: 'Weihnachten',
    fi: 'Joulu',
  },
  'New Year': {
    sv: 'Nyår',
    no: 'Nyttår',
    da: 'Nytår',
    de: 'Neujahr',
    fi: 'Uusi vuosi',
  },
  'Winter wonderland': {
    sv: 'Vinterland',
    no: 'Vinterland',
    da: 'Vinterland',
    de: 'Winterwunderland',
    fi: 'Talvimaa',
  },
  'Spring flowers': {
    sv: 'Vårblommor',
    no: 'Vårblomster',
    da: 'Forårsblomster',
    de: 'Frühlingsblumen',
    fi: 'Kevätkukat',
  },
  'Summer vibes': {
    sv: 'Sommarkänsla',
    no: 'Sommerstemning',
    da: 'Sommerstemning',
    de: 'Sommervibes',
    fi: 'Kesäfiilis',
  },
  'Autumn colors': {
    sv: 'Höstfärger',
    no: 'Høstfarger',
    da: 'Efterårsfarver',
    de: 'Herbstfarben',
    fi: 'Syksyn värit',
  },
  Valentine: {
    sv: 'Alla hjärtans dag',
    no: 'Valentinsdag',
    da: 'Valentinsdag',
    de: 'Valentinstag',
    fi: 'Ystävänpäivä',
  },
  Halloween: {
    sv: 'Halloween',
    no: 'Halloween',
    da: 'Halloween',
    de: 'Halloween',
    fi: 'Halloween',
  },
  'Curated collection': {
    sv: 'Kuraterad samling',
    no: 'Kuratert samling',
    da: 'Kurateret samling',
    de: 'Kuratierte Sammlung',
    fi: 'Kuratoitu kokoelma',
  },
  'Winter sports': {
    sv: 'Vintersport',
    no: 'Vintersport',
    da: 'Vintersport',
    de: 'Wintersport',
    fi: 'Talviurheilu',
  },
  'Cozy moments': {
    sv: 'Mysiga stunder',
    no: 'Koselige øyeblikk',
    da: 'Hyggelige øjeblikke',
    de: 'Gemütliche Momente',
    fi: 'Kodikkaat hetket',
  },
  Easter: {
    sv: 'Påsk',
    no: 'Påske',
    da: 'Påske',
    de: 'Ostern',
    fi: 'Pääsiäinen',
  },
  'Cherry blossoms': {
    sv: 'Körsbärsblom',
    no: 'Kirsebærblomster',
    da: 'Kirsebærblomster',
    de: 'Kirschblüten',
    fi: 'Kirsikankukat',
  },
  'Earth Day': {
    sv: 'Jordens dag',
    no: 'Jordens dag',
    da: 'Jordens dag',
    de: 'Tag der Erde',
    fi: 'Maapallon päivä',
  },
  Tulips: {
    sv: 'Tulpaner',
    no: 'Tulipaner',
    da: 'Tulipaner',
    de: 'Tulpen',
    fi: 'Tulppaanit',
  },
  Gardens: {
    sv: 'Trädgårdar',
    no: 'Hager',
    da: 'Haver',
    de: 'Gärten',
    fi: 'Puutarhat',
  },
  Butterflies: {
    sv: 'Fjärilar',
    no: 'Sommerfugler',
    da: 'Sommerfugle',
    de: 'Schmetterlinge',
    fi: 'Perhoset',
  },
  Pride: {
    sv: 'Pride',
    no: 'Pride',
    da: 'Pride',
    de: 'Pride',
    fi: 'Pride',
  },
  'Tropical paradise': {
    sv: 'Tropiskt paradis',
    no: 'Tropisk paradis',
    da: 'Tropisk paradis',
    de: 'Tropisches Paradies',
    fi: 'Trooppinen paratiisi',
  },
  'Summer vacation': {
    sv: 'Sommarlov',
    no: 'Sommerferie',
    da: 'Sommerferie',
    de: 'Sommerferien',
    fi: 'Kesäloma',
  },
  Sunflowers: {
    sv: 'Solrosor',
    no: 'Solsikker',
    da: 'Solsikker',
    de: 'Sonnenblumen',
    fi: 'Auringonkukat',
  },
  Camping: {
    sv: 'Camping',
    no: 'Camping',
    da: 'Camping',
    de: 'Camping',
    fi: 'Leirintä',
  },
  Sunsets: {
    sv: 'Solnedgångar',
    no: 'Solnedganger',
    da: 'Solnedgange',
    de: 'Sonnenuntergänge',
    fi: 'Auringonlaskut',
  },
  'Harvest time': {
    sv: 'Skördetid',
    no: 'Høstetid',
    da: 'Høsttid',
    de: 'Erntezeit',
    fi: 'Sadonkorjuuaika',
  },
  'Cozy autumn': {
    sv: 'Mysig höst',
    no: 'Koselig høst',
    da: 'Hyggelig efterår',
    de: 'Gemütlicher Herbst',
    fi: 'Kodikas syksy',
  },
  'Fall foliage': {
    sv: 'Höstlöv',
    no: 'Høstløv',
    da: 'Efterårsblade',
    de: 'Herbstlaub',
    fi: 'Syksyn lehdet',
  },
  Thanksgiving: {
    sv: 'Tacksägelse',
    no: 'Thanksgiving',
    da: 'Thanksgiving',
    de: 'Erntedankfest',
    fi: 'Kiitospäivä',
  },
  'Cozy hygge': {
    sv: 'Mysig hygge',
    no: 'Koselig hygge',
    da: 'Hyggeligt hygge',
    de: 'Gemütliches Hygge',
    fi: 'Kodikas hygge',
  },
  'Winter magic': {
    sv: 'Vintermagi',
    no: 'Vintermagi',
    da: 'Vintermagi',
    de: 'Winterzauber',
    fi: 'Talven taikaa',
  },
  Cats: {
    sv: 'Katter',
    no: 'Katter',
    da: 'Katte',
    de: 'Katzen',
    fi: 'Kissat',
  },
  'Beautiful oceans': {
    sv: 'Vackra hav',
    no: 'Vakre hav',
    da: 'Smukke have',
    de: 'Schöne Ozeane',
    fi: 'Kauniit valtameret',
  },
  Nature: {
    sv: 'Naturen',
    no: 'Naturen',
    da: 'Naturen',
    de: 'Natur',
    fi: 'Luonto',
  },
  Animals: {
    sv: 'Djur',
    no: 'Dyr',
    da: 'Dyr',
    de: 'Tiere',
    fi: 'Eläimet',
  },
  Forests: {
    sv: 'I skogen',
    no: 'I skogen',
    da: 'I skoven',
    de: 'Im Wald',
    fi: 'Metsissä',
  },
  People: {
    sv: 'Människor',
    no: 'Mennesker',
    da: 'Mennesker',
    de: 'Menschen',
    fi: 'Ihmiset',
  },
  'In the mountains': {
    sv: 'Uppe på begen',
    no: 'På fjellet',
    da: 'I bjergene',
    de: 'In den Bergen',
    fi: 'Vuorilla',
  },
  Greece: {
    sv: 'Grekland',
    no: 'Hellas',
    da: 'Grækenland',
    de: 'Griechenland',
    fi: 'Kreikka',
  },
  Sport: {
    sv: 'Sport',
    no: 'Sport',
    da: 'Sport',
    de: 'Sport',
    fi: 'Urheilu',
  },
  Cities: {
    sv: 'Städer',
    no: 'Byer',
    da: 'Byer',
    de: 'Städte',
    fi: 'Kaupungit',
  },
  Babies: {
    sv: 'Bebisar',
    no: 'Babyer',
    da: 'Babyer',
    de: 'Babys',
    fi: 'Vauvat',
  },
  Flowers: {
    sv: 'Blommor',
    no: 'Blomster',
    da: 'Blomster',
    de: 'Blumen',
    fi: 'Kukat',
  },
  Cars: {
    sv: 'Bilar',
    no: 'Biler',
    da: 'Biler',
    de: 'Autos',
    fi: 'Autot',
  },
  Architecture: {
    sv: 'Arkitektur',
    no: 'Arkitektur',
    da: 'Arkitektur',
    de: 'Architektur',
    fi: 'Arkkitehtuuri',
  },
  Coffee: {
    sv: 'Kaffe',
    no: 'Kaffe',
    da: 'Kaffe',
    de: 'Kaffee',
    fi: 'Kahvi',
  },
  Food: {
    sv: 'Mat',
    no: 'Mat',
    da: 'Mad',
    de: 'Essen',
    fi: 'Ruoka',
  },
  Waterfalls: {
    sv: 'Vattenfall',
    no: 'Fosser',
    da: 'Vandfald',
    de: 'Wasserfälle',
    fi: 'Vesiputoukset',
  },
  Wildlife: {
    sv: 'Vilda djur',
    no: 'Ville dyr',
    da: 'Vilde dyr',
    de: 'Wildtiere',
    fi: 'Luonnonvaraiset eläimet',
  },
  Birds: {
    sv: 'Fåglar',
    no: 'Fugler',
    da: 'Fugle',
    de: 'Vögel',
    fi: 'Linnut',
  },
  'Outer space': {
    sv: 'Rymden',
    no: 'Rommet',
    da: 'Rummet',
    de: 'Weltraum',
    fi: 'Avaruus',
  },
  Vintage: {
    sv: 'Vintage',
    no: 'Vintage',
    da: 'Vintage',
    de: 'Vintage',
    fi: 'Vintage',
  },
  Abstract: {
    sv: 'Abstrakt',
    no: 'Abstrakt',
    da: 'Abstrakt',
    de: 'Abstrakt',
    fi: 'Abstrakti',
  },
  // --- Categories ---
} as const;
