const icon = {
	"Burn solid": "\uf46a",
	"Bullseye solid": "\uf140",
	"bullhorn solid": "\uf0a1",
	"Building solid": "\uf1ad",
	"Building regular": "\uf1ad",
	"Bug solid": "\uf188",
	"BTC brands": "\uf15a",
	"Medical Briefcase solid": "\uf469",
	"Briefcase solid": "\uf0b1",
	"Braille solid": "\uf2a1",
	"Boxes solid": "\uf468",
	"Box Open solid": "\uf49e",
	"Box solid": "\uf466",
	"Bowling Ball solid": "\uf436",
	"bookmark solid": "\uf02e",
	"bookmark regular": "\uf02e",
	"book solid": "\uf02d",
	"Bomb solid": "\uf1e2",
	"Lightning Bolt solid": "\uf0e7",
	"bold solid": "\uf032",
	"Bluetooth brands": "\uf294",
	"Bluetooth brands alt": "\uf293",
	"Blogger B brands": "\uf37d",
	"Blogger brands": "\uf37c",
	"Blind solid": "\uf29d",
	"BlackBerry brands": "\uf37b",
	"Font Awesome Black Tie brands": "\uf27e",
	"Bity brands": "\uf37a",
	"Bitcoin brands": "\uf379",
	"Bitbucket brands": "\uf171",
	"Birthday Cake solid": "\uf1fd",
	"Binoculars solid": "\uf1e5",
	"BIMobject brands": "\uf378",
	"Bicycle solid": "\uf206",
	"Bell Slash solid": "\uf1f6",
	"Bell Slash regular": "\uf1f6",
	"bell solid": "\uf0f3",
	"bell regular": "\uf0f3",
	"Behance Square brands": "\uf1b5",
	"Behance brands": "\uf1b4",
	"beer solid": "\uf0fc",
	"Bed solid": "\uf236",
	"Battery 3\/4 Full solid": "\uf241",
	"Battery 1\/4 Full solid": "\uf243",
	"Battery 1\/2 Full solid": "\uf242",
	"Battery Full solid": "\uf240",
	"Battery Empty solid": "\uf244",
	"Bath solid": "\uf2cd",
	"Basketball Ball solid": "\uf434",
	"Baseball Ball solid": "\uf433",
	"Bars solid": "\uf0c9",
	"barcode solid": "\uf02a",
	"Bandcamp brands": "\uf2d5",
	"Band-Aid solid": "\uf462",
	"ban solid": "\uf05e",
	"Balance Scale solid": "\uf24e",
	"backward solid": "\uf04a",
	"Amazon Web Services (AWS) brands": "\uf375",
	"Aviato brands": "\uf421",
	"avianex brands": "\uf374",
	"Autoprefixer brands": "\uf41c",
	"Audio Description solid": "\uf29e",
	"Audible brands": "\uf373",
	"At solid": "\uf1fa",
	"Asymmetrik, Ltd. brands": "\uf372",
	"asterisk solid": "\uf069",
	"Assistive Listening Systems solid": "\uf2a2",
	"Alternate Arrows Vertical solid": "\uf338",
	"Alternate Arrows Horizontal solid": "\uf337",
	"Alternate Arrows solid": "\uf0b2",
	"arrow-up solid": "\uf062",
	"arrow-right solid": "\uf061",
	"arrow-left solid": "\uf060",
	"arrow-down solid": "\uf063",
	"Arrow Circle Up solid": "\uf0aa",
	"Arrow Circle Right solid": "\uf0a9",
	"Arrow Circle Left solid": "\uf0a8",
	"Arrow Circle Down solid": "\uf0ab",
	"Alternate Arrow Circle Up solid": "\uf35b",
	"Alternate Arrow Circle Up regular": "\uf35b",
	"Alternate Arrow Circle Right solid": "\uf35a",
	"Alternate Arrow Circle Right regular": "\uf35a",
	"Alternate Arrow Circle Left solid": "\uf359",
	"Alternate Arrow Circle Left regular": "\uf359",
	"Alternate Arrow Circle Down solid": "\uf358",
	"Alternate Arrow Circle Down regular": "\uf358",
	"Archive solid": "\uf187",
	"Apple Pay brands": "\uf415",
	"Apple brands": "\uf179",
	"Apper Systems AB brands": "\uf371",
	"iOS App Store brands": "\uf370",
	"App Store brands": "\uf36f",
	"Angular brands": "\uf420",
	"Angry Creative brands": "\uf36e",
	"angle-up solid": "\uf106",
	"angle-right solid": "\uf105",
	"angle-left solid": "\uf104",
	"angle-down solid": "\uf107",
	"Angle Double Up solid": "\uf102",
	"Angle Double Right solid": "\uf101",
	"Angle Double Left solid": "\uf100",
	"Angle Double Down solid": "\uf103",
	"AngelList brands": "\uf209",
	"Android brands": "\uf17b",
	"Anchor solid": "\uf13d",
	"Amilia brands": "\uf36d",
	"American Sign Language Interpreting solid": "\uf2a3",
	"ambulance solid": "\uf0f9",
	"Amazon Pay brands": "\uf42c",
	"Amazon brands": "\uf270",
	"Allergies solid": "\uf461",
	"align-right solid": "\uf038",
	"align-left solid": "\uf036",
	"align-justify solid": "\uf039",
	"align-center solid": "\uf037",
	"Algolia brands": "\uf36c",
	"affiliatetheme brands": "\uf36b",
	"Adversal brands": "\uf36a",
	"App.net brands": "\uf170",
	"adjust solid": "\uf042",
	"Address Card solid": "\uf2bb",
	"Address Card regular": "\uf2bb",
	"Address Book solid": "\uf2b9",
	"Address Book regular": "\uf2b9",
	"Accusoft brands": "\uf369",
	"Accessible Icon brands": "\uf368",
	"500px brands": "\uf26e",
	"YouTube Square brands": "\uf431",
	"YouTube brands": "\uf167",
	"Yoast brands": "\uf2b1",
	"Yen Sign solid": "\uf157",
	"Yelp brands": "\uf1e9",
	"Yandex International brands": "\uf414",
	"Yandex brands": "\uf413",
	"Yahoo Logo brands": "\uf19e",
	"Y Combinator brands": "\uf23b",
	"Xing Square brands": "\uf169",
	"Xing brands": "\uf168",
	"Xbox brands": "\uf412",
	"X-Ray solid": "\uf497",
	"Wrench solid": "\uf0ad",
	"WPForms brands": "\uf298",
	"WPExplorer brands": "\uf2de",
	"WPBeginner brands": "\uf297",
	"Wordpress Simple brands": "\uf411",
	"WordPress Logo brands": "\uf19a",
	"Won Sign solid": "\uf159",
	"Wolf Pack-battalion brands": "\uf514",
	"Wine Glass solid": "\uf4e3",
	"Windows brands": "\uf17a",
	"Window Restore solid": "\uf2d2",
	"Window Restore regular": "\uf2d2",
	"Window Minimize solid": "\uf2d1",
	"Window Minimize regular": "\uf2d1",
	"Window Maximize solid": "\uf2d0",
	"Window Maximize regular": "\uf2d0",
	"Window Close solid": "\uf410",
	"Window Close regular": "\uf410",
	"Wikipedia W brands": "\uf266",
	"WiFi solid": "\uf1eb",
	"WHMCS brands": "\uf40d",
	"Wheelchair solid": "\uf193",
	"What's App Square brands": "\uf40c",
	"What's App brands": "\uf232",
	"Weixin (WeChat) brands": "\uf1d7",
	"Weight solid": "\uf496",
	"Weibo brands": "\uf18a",
	"Warehouse solid": "\uf494",
	"Vue.js brands": "\uf41f",
	"volume-up solid": "\uf028",
	"volume-off solid": "\uf026",
	"volume-down solid": "\uf027",
	"Volleyball Ball solid": "\uf45f",
	"VNV brands": "\uf40b",
	"VK brands": "\uf189",
	"Vine brands": "\uf1ca",
	"Vimeo brands": "\uf27d",
	"Vimeo Square brands": "\uf194",
	"Vimeo brands alt": "\uf40a",
	"Video Slash solid": "\uf4e2",
	"Video solid": "\uf03d",
	"Viber brands": "\uf409",
	"Vials solid": "\uf493",
	"Vial solid": "\uf492",
	"Viadeo Square brands": "\uf2aa",
	"Viadeo brands": "\uf2a9",
	"Viacoin brands": "\uf237",
	"Venus Mars solid": "\uf228",
	"Venus Double solid": "\uf226",
	"Venus solid": "\uf221",
	"Vaadin brands": "\uf408",
	"Utensils solid": "\uf2e7",
	"Utensil Spoon solid": "\uf2e5",
	"us-Sunnah Foundation brands": "\uf407",
	"Users Cog solid": "\uf509",
	"Users solid": "\uf0c0",
	"Remove User solid": "\uf235",
	"User Tie solid": "\uf508",
	"User Tag solid": "\uf507",
	"User Slash solid": "\uf506",
	"User Shield solid": "\uf505",
	"User Secret solid": "\uf21b",
	"Add User solid": "\uf234",
	"User Ninja solid": "\uf504",
	"User Minus solid": "\uf503",
	"user-md solid": "\uf0f0",
	"User Lock solid": "\uf502",
	"User Graduate solid": "\uf501",
	"User Friends solid": "\uf500",
	"User Edit solid": "\uf4ff",
	"User Cog solid": "\uf4fe",
	"User Clock solid": "\uf4fd",
	"User Circle solid": "\uf2bd",
	"User Circle regular": "\uf2bd",
	"User Check solid": "\uf4fc",
	"User Astronaut solid": "\uf4fb",
	"User Alt-slash solid": "\uf4fa",
	"Alternate User solid": "\uf406",
	"User solid": "\uf007",
	"User regular": "\uf007",
	"USB brands": "\uf287",
	"Upload solid": "\uf093",
	"Untappd brands": "\uf405",
	"Alternate Unlock solid": "\uf13e",
	"unlock solid": "\uf09c",
	"unlink solid": "\uf127",
	"University solid": "\uf19c",
	"Universal Access solid": "\uf29a",
	"Uniregistry brands": "\uf404",
	"Alternate Undo solid": "\uf2ea",
	"Undo solid": "\uf0e2",
	"Underline solid": "\uf0cd",
	"Umbrella solid": "\uf0e9",
	"UIkit brands": "\uf403",
	"Uber brands": "\uf402",
	"Typo3 brands": "\uf42b",
	"Twitter Square brands": "\uf081",
	"Twitter brands": "\uf099",
	"Twitch brands": "\uf1e8",
	"Television solid": "\uf26c",
	"Tumblr Square brands": "\uf174",
	"Tumblr brands": "\uf173",
	"TTY solid": "\uf1e4",
	"Truck Moving solid": "\uf4df",
	"Truck Loading solid": "\uf4de",
	"truck solid": "\uf0d1",
	"trophy solid": "\uf091",
	"TripAdvisor brands": "\uf262",
	"Trello brands": "\uf181",
	"Tree solid": "\uf1bb",
	"Alternate Trash solid": "\uf2ed",
	"Alternate Trash regular": "\uf2ed",
	"Trash solid": "\uf1f8",
	"Alternate Transgender solid": "\uf225",
	"Transgender solid": "\uf224",
	"Train solid": "\uf238",
	"Trademark solid": "\uf25c",
	"Trade Federation brands": "\uf513",
	"Toggle On solid": "\uf205",
	"Toggle Off solid": "\uf204",
	"tint solid": "\uf043",
	"Times Circle solid": "\uf057",
	"Times Circle regular": "\uf057",
	"Times solid": "\uf00d",
	"Alternate Ticket solid": "\uf3ff",
	"Thumbtack solid": "\uf08d",
	"thumbs-up solid": "\uf164",
	"thumbs-up regular": "\uf164",
	"thumbs-down solid": "\uf165",
	"thumbs-down regular": "\uf165",
	"Thermometer 3\/4 Full solid": "\uf2c8",
	"Thermometer 1\/4 Full solid": "\uf2ca",
	"Thermometer 1\/2 Full solid": "\uf2c9",
	"Thermometer Full solid": "\uf2c7",
	"Thermometer Empty solid": "\uf2cb",
	"Thermometer solid": "\uf491",
	"ThemeIsle brands": "\uf2b2",
	"th-list solid": "\uf00b",
	"th-large solid": "\uf009",
	"th solid": "\uf00a",
	"text-width solid": "\uf035",
	"text-height solid": "\uf034",
	"Terminal solid": "\uf120",
	"Tencent Weibo brands": "\uf1d5",
	"Telegram Plane brands": "\uf3fe",
	"Telegram brands": "\uf2c6",
	"TeamSpeak brands": "\uf4f9",
	"Taxi solid": "\uf1ba",
	"Tasks solid": "\uf0ae",
	"Tape solid": "\uf4db",
	"tags solid": "\uf02c",
	"tag solid": "\uf02b",
	"Alternate Tachometer solid": "\uf3fd",
	"Tablets solid": "\uf490",
	"Alternate Tablet solid": "\uf3fa",
	"tablet solid": "\uf10a",
	"Table Tennis solid": "\uf45d",
	"table solid": "\uf0ce",
	"Syringe solid": "\uf48e",
	"Alternate Sync solid": "\uf2f1",
	"Sync solid": "\uf021",
	"Supple brands": "\uf3f9",
	"superscript solid": "\uf12b",
	"Superpowers brands": "\uf2dd",
	"Sun solid": "\uf185",
	"Sun regular": "\uf185",
	"Suitcase solid": "\uf0f2",
	"Subway solid": "\uf239",
	"subscript solid": "\uf12c",
	"StumbleUpon Circle brands": "\uf1a3",
	"StumbleUpon Logo brands": "\uf1a4",
	"Studio Vinari brands": "\uf3f8",
	"Stripe S brands": "\uf42a",
	"Stripe brands": "\uf429",
	"Strikethrough solid": "\uf0cc",
	"Street View solid": "\uf21d",
	"Strava brands": "\uf428",
	"Stopwatch solid": "\uf2f2",
	"Stop Circle solid": "\uf28d",
	"Stop Circle regular": "\uf28d",
	"stop solid": "\uf04d",
	"Sticky Note solid": "\uf249",
	"Sticky Note regular": "\uf249",
	"Sticker Mule brands": "\uf3f7",
	"Stethoscope solid": "\uf0f1",
	"step-forward solid": "\uf051",
	"step-backward solid": "\uf048",
	"Steam Symbol brands": "\uf3f6",
	"Steam Square brands": "\uf1b7",
	"Steam brands": "\uf1b6",
	"StayLinked brands": "\uf3f5",
	"star-half solid": "\uf089",
	"star-half regular": "\uf089",
	"Star solid": "\uf005",
	"Star regular": "\uf005",
	"Stack Overflow brands": "\uf16c",
	"Stack Exchange brands": "\uf18d",
	"Square Full solid": "\uf45c",
	"Square solid": "\uf0c8",
	"Square regular": "\uf0c8",
	"Spotify brands": "\uf1bc",
	"Spinner solid": "\uf110",
	"Speakap brands": "\uf3f3",
	"Space Shuttle solid": "\uf197",
	"SoundCloud brands": "\uf1be",
	"Sort Up (Ascending) solid": "\uf0de",
	"Sort Numeric Up solid": "\uf163",
	"Sort Numeric Down solid": "\uf162",
	"Sort Down (Descending) solid": "\uf0dd",
	"Sort Amount Up solid": "\uf161",
	"Sort Amount Down solid": "\uf160",
	"Sort Alpha Up solid": "\uf15e",
	"Sort Alpha Down solid": "\uf15d",
	"Sort solid": "\uf0dc",
	"Snowflake solid": "\uf2dc",
	"Snowflake regular": "\uf2dc",
	"Snapchat Square brands": "\uf2ad",
	"Snapchat Ghost brands": "\uf2ac",
	"Snapchat brands": "\uf2ab",
	"Smoking solid": "\uf48d",
	"Smile solid": "\uf118",
	"Smile regular": "\uf118",
	"Slideshare brands": "\uf1e7",
	"Horizontal Sliders solid": "\uf1de",
	"Slack Hashtag brands": "\uf3ef",
	"Slack Logo brands": "\uf198",
	"Skype brands": "\uf17e",
	"skyatlas brands": "\uf216",
	"Sith brands": "\uf512",
	"Sitemap solid": "\uf0e8",
	"SISTRIX brands": "\uf3ee",
	"SimplyBuilt brands": "\uf215",
	"signal solid": "\uf012",
	"Alternate Sign Out solid": "\uf2f5",
	"Sign Language solid": "\uf2a7",
	"Alternate Sign In solid": "\uf2f6",
	"Sign solid": "\uf4d9",
	"Shower solid": "\uf2cc",
	"shopping-cart solid": "\uf07a",
	"Shopping Basket solid": "\uf291",
	"Shopping Bag solid": "\uf290",
	"Shirts in Bulk brands": "\uf214",
	"Shipping Fast solid": "\uf48b",
	"Ship solid": "\uf21a",
	"Alternate Shield solid": "\uf3ed",
	"Shekel Sign solid": "\uf20b",
	"Share Square solid": "\uf14d",
	"Share Square regular": "\uf14d",
	"Alternate Share Square solid": "\uf1e1",
	"Alternate Share solid": "\uf1e0",
	"Share solid": "\uf064",
	"Servicestack brands": "\uf3ec",
	"Server solid": "\uf233",
	"Sellsy brands": "\uf213",
	"Sellcast brands": "\uf2da",
	"Seedling solid": "\uf4d8",
	"Searchengin brands": "\uf3eb",
	"Search Plus solid": "\uf00e",
	"Search Minus solid": "\uf010",
	"Search solid": "\uf002",
	"Scribd brands": "\uf28a",
	"SCHLIX brands": "\uf3ea",
	"Save solid": "\uf0c7",
	"Save regular": "\uf0c7",
	"Sass brands": "\uf41e",
	"Safari brands": "\uf267",
	"Indian Rupee Sign solid": "\uf156",
	"Ruble Sign solid": "\uf158",
	"RSS Square solid": "\uf143",
	"rss solid": "\uf09e",
	"Rockrms brands": "\uf3e9",
	"Rocket.Chat brands": "\uf3e8",
	"rocket solid": "\uf135",
	"road solid": "\uf018",
	"Ribbon solid": "\uf4d6",
	"Retweet solid": "\uf079",
	"Resolving brands": "\uf3e7",
	"Researchgate brands": "\uf4f8",
	"replyd brands": "\uf3e6",
	"reply-all solid": "\uf122",
	"Reply solid": "\uf3e5",
	"Renren brands": "\uf18b",
	"Rendact brands": "\uf3e4",
	"Registered Trademark solid": "\uf25d",
	"Registered Trademark regular": "\uf25d",
	"Alternate Redo solid": "\uf2f9",
	"Redo solid": "\uf01e",
	"reddit Square brands": "\uf1a2",
	"reddit Alien brands": "\uf281",
	"reddit Logo brands": "\uf1a1",
	"red river brands": "\uf3e3",
	"Recycle solid": "\uf1b8",
	"Rebel Alliance brands": "\uf1d0",
	"ReadMe brands": "\uf4d5",
	"React brands": "\uf41b",
	"Ravelry brands": "\uf2d9",
	"random solid": "\uf074",
	"R Project brands": "\uf4f7",
	"quote-right solid": "\uf10e",
	"quote-left solid": "\uf10d",
	"Quora brands": "\uf2c4",
	"QuinScape brands": "\uf459",
	"Quidditch solid": "\uf458",
	"Question Circle solid": "\uf059",
	"Question Circle regular": "\uf059",
	"Question solid": "\uf128",
	"qrcode solid": "\uf029",
	"QQ brands": "\uf1d6",
	"Python brands": "\uf3e2",
	"Puzzle Piece solid": "\uf12e",
	"Pushed brands": "\uf3e1",
	"Product Hunt brands": "\uf288",
	"Procedures solid": "\uf487",
	"print solid": "\uf02f",
	"Alternate Prescription Bottle solid": "\uf486",
	"Prescription Bottle solid": "\uf485",
	"Power Off solid": "\uf011",
	"Pound Sign solid": "\uf154",
	"Portrait solid": "\uf3e0",
	"Poo solid": "\uf2fe",
	"Podcast solid": "\uf2ce",
	"Plus Square solid": "\uf0fe",
	"Plus Square regular": "\uf0fe",
	"Plus Circle solid": "\uf055",
	"plus solid": "\uf067",
	"Plug solid": "\uf1e6",
	"PlayStation brands": "\uf3df",
	"Play Circle solid": "\uf144",
	"Play Circle regular": "\uf144",
	"play solid": "\uf04b",
	"plane solid": "\uf072",
	"Pinterest Square brands": "\uf0d3",
	"Pinterest P brands": "\uf231",
	"Pinterest brands": "\uf0d2",
	"Pills solid": "\uf484",
	"Piggy Bank solid": "\uf4d3",
	"Pied Piper PP Logo (Old) brands": "\uf1a7",
	"Pied Piper-hat brands": "\uf4e5",
	"Alternate Pied Piper Logo brands": "\uf1a8",
	"Pied Piper Logo brands": "\uf2ae",
	"PHP brands": "\uf457",
	"Phone Volume solid": "\uf2a0",
	"Phone Square solid": "\uf098",
	"Phone Slash solid": "\uf3dd",
	"Phone solid": "\uf095",
	"Phoenix Squadron brands": "\uf511",
	"Phoenix Framework brands": "\uf3dc",
	"Phabricator brands": "\uf3db",
	"Periscope brands": "\uf3da",
	"Percent solid": "\uf295",
	"People Carry solid": "\uf4ce",
	"Alternate Pencil solid": "\uf303",
	"Pen Square solid": "\uf14b",
	"Paypal brands": "\uf1ed",
	"Paw solid": "\uf1b0",
	"Pause Circle solid": "\uf28b",
	"Pause Circle regular": "\uf28b",
	"pause solid": "\uf04c",
	"Patreon brands": "\uf3d9",
	"Paste solid": "\uf0ea",
	"paragraph solid": "\uf1dd",
	"Parachute Box solid": "\uf4cd",
	"Paperclip solid": "\uf0c6",
	"Paper Plane solid": "\uf1d8",
	"Paper Plane regular": "\uf1d8",
	"Pallet solid": "\uf482",
	"Palfed brands": "\uf3d8",
	"Paint Brush solid": "\uf1fc",
	"Pagelines brands": "\uf18c",
	"page4 Corporation brands": "\uf3d7",
	"Outdent solid": "\uf03b",
	"Open Source Initiative brands": "\uf41a",
	"Optin Monster brands": "\uf23c",
	"Opera brands": "\uf26a",
	"OpenID brands": "\uf19b",
	"OpenCart brands": "\uf23d",
	"Old Republic brands": "\uf510",
	"Odnoklassniki Square brands": "\uf264",
	"Odnoklassniki brands": "\uf263",
	"Object Ungroup solid": "\uf248",
	"Object Ungroup regular": "\uf248",
	"Object Group solid": "\uf247",
	"Object Group regular": "\uf247",
	"Nutritionix brands": "\uf3d6",
	"NS8 brands": "\uf3d5",
	"npm brands": "\uf3d4",
	"Medical Notes solid": "\uf481",
	"Node.js JS brands": "\uf3d3",
	"Node.js brands": "\uf419",
	"Nintendo Switch brands": "\uf418",
	"Newspaper solid": "\uf1ea",
	"Newspaper regular": "\uf1ea",
	"Neuter solid": "\uf22c",
	"Napster brands": "\uf3d2",
	"Music solid": "\uf001",
	"Mouse Pointer solid": "\uf245",
	"Motorcycle solid": "\uf21c",
	"Moon solid": "\uf186",
	"Moon regular": "\uf186",
	"Money Bill Alternate solid": "\uf3d1",
	"Money Bill Alternate regular": "\uf3d1",
	"Monero brands": "\uf3d0",
	"MODX brands": "\uf285",
	"Alternate Mobile solid": "\uf3cd",
	"Mobile Phone solid": "\uf10b",
	"Mizuni brands": "\uf3cc",
	"Mixcloud brands": "\uf289",
	"Mix brands": "\uf3cb",
	"Minus Square solid": "\uf146",
	"Minus Square regular": "\uf146",
	"Minus Circle solid": "\uf056",
	"minus solid": "\uf068",
	"Microsoft brands": "\uf3ca",
	"Microphone Slash solid": "\uf131",
	"microphone solid": "\uf130",
	"Microchip solid": "\uf2db",
	"Mercury solid": "\uf223",
	"Meh solid": "\uf11a",
	"Meh regular": "\uf11a",
	"Meetup brands": "\uf2e0",
	"MRT brands": "\uf3c8",
	"medkit solid": "\uf0fa",
	"Medium M brands": "\uf3c7",
	"Medium brands": "\uf23a",
	"MedApps brands": "\uf3c6",
	"MaxCDN brands": "\uf136",
	"Mastodon brands": "\uf4f6",
	"Mars Stroke Vertical solid": "\uf22a",
	"Mars Stroke Horizontal solid": "\uf22b",
	"Mars Stroke solid": "\uf229",
	"Mars Double solid": "\uf227",
	"Mars solid": "\uf222",
	"Map Signs solid": "\uf277",
	"Map Pin solid": "\uf276",
	"Map Marker Alternate solid": "\uf3c5",
	"map-marker solid": "\uf041",
	"Map solid": "\uf279",
	"Map regular": "\uf279",
	"Mandalorian brands": "\uf50f",
	"Male solid": "\uf183",
	"magnet solid": "\uf076",
	"magic solid": "\uf0d0",
	"Magento brands": "\uf3c4",
	"lyft brands": "\uf3c3",
	"Low Vision solid": "\uf2a8",
	"Alternate Long Arrow Up solid": "\uf30c",
	"Alternate Long Arrow Right solid": "\uf30b",
	"Alternate Long Arrow Left solid": "\uf30a",
	"Alternate Long Arrow Down solid": "\uf309",
	"Lock Open solid": "\uf3c1",
	"lock solid": "\uf023",
	"location-arrow solid": "\uf124",
	"list-ul solid": "\uf0ca",
	"list-ol solid": "\uf0cb",
	"List Alternate solid": "\uf022",
	"List Alternate regular": "\uf022",
	"List solid": "\uf03a",
	"Turkish Lira Sign solid": "\uf195",
	"Linux brands": "\uf17c",
	"Linode brands": "\uf2b8",
	"LinkedIn In brands": "\uf0e1",
	"LinkedIn brands": "\uf08c",
	"Link solid": "\uf0c1",
	"Line brands": "\uf3c0",
	"Lightbulb solid": "\uf0eb",
	"Lightbulb regular": "\uf0eb",
	"Life Ring solid": "\uf1cd",
	"Life Ring regular": "\uf1cd",
	"Level Up Alternate solid": "\uf3bf",
	"Level Down Alternate solid": "\uf3be",
	"Less brands": "\uf41d",
	"Lemon solid": "\uf094",
	"Lemon regular": "\uf094",
	"Leanpub brands": "\uf212",
	"leaf solid": "\uf06c",
	"last.fm Square brands": "\uf203",
	"last.fm brands": "\uf202",
	"Laravel brands": "\uf3bd",
	"Laptop solid": "\uf109",
	"Language solid": "\uf1ab",
	"KORVUE brands": "\uf42f",
	"Kickstarter K brands": "\uf3bc",
	"Kickstarter brands": "\uf3bb",
	"KeyCDN brands": "\uf3ba",
	"Keyboard solid": "\uf11c",
	"Keyboard regular": "\uf11c",
	"Keybase brands": "\uf4f5",
	"key solid": "\uf084",
	"jsFiddle brands": "\uf1cc",
	"JavaScript (JS) Square brands": "\uf3b9",
	"JavaScript (JS) brands": "\uf3b8",
	"Joomla Logo brands": "\uf1aa",
	"Joget brands": "\uf3b7",
	"Jenkis brands": "\uf3b6",
	"Jedi Order brands": "\uf50e",
	"Java brands": "\uf4e4",
	"Itunes Note brands": "\uf3b5",
	"iTunes brands": "\uf3b4",
	"italic solid": "\uf033",
	"ioxhost brands": "\uf208",
	"Internet-explorer brands": "\uf26b",
	"Instagram brands": "\uf16d",
	"Info Circle solid": "\uf05a",
	"Info solid": "\uf129",
	"Industry solid": "\uf275",
	"Indent solid": "\uf03c",
	"inbox solid": "\uf01c",
	"IMDB brands": "\uf2d8",
	"Images solid": "\uf302",
	"Images regular": "\uf302",
	"Image solid": "\uf03e",
	"Image regular": "\uf03e",
	"Identification Card Alternate solid": "\uf47f",
	"Identification Card solid": "\uf2c2",
	"Identification Card regular": "\uf2c2",
	"Identification Badge solid": "\uf2c1",
	"Identification Badge regular": "\uf2c1",
	"I Beam Cursor solid": "\uf246",
	"HubSpot brands": "\uf3b2",
	"HTML 5 Logo brands": "\uf13b",
	"Houzz brands": "\uf27c",
	"Hourglass Start solid": "\uf251",
	"Hourglass Half solid": "\uf252",
	"Hourglass End solid": "\uf253",
	"Hourglass solid": "\uf254",
	"Hourglass regular": "\uf254",
	"Hotjar brands": "\uf3b1",
	"Hospital Symbol solid": "\uf47e",
	"Hospital Alternate solid": "\uf47d",
	"hospital solid": "\uf0f8",
	"hospital regular": "\uf0f8",
	"Hooli brands": "\uf427",
	"home solid": "\uf015",
	"Hockey Puck solid": "\uf453",
	"History solid": "\uf1da",
	"HireAHelper brands": "\uf3b0",
	"Hips brands": "\uf452",
	"Heartbeat solid": "\uf21e",
	"Heart solid": "\uf004",
	"Heart regular": "\uf004",
	"headphones solid": "\uf025",
	"heading solid": "\uf1dc",
	"HDD solid": "\uf0a0",
	"HDD regular": "\uf0a0",
	"Hashtag solid": "\uf292",
	"Handshake solid": "\uf2b5",
	"Handshake regular": "\uf2b5",
	"Helping Hands solid": "\uf4c4",
	"Hands solid": "\uf4c2",
	"Spock (Hand) solid": "\uf259",
	"Spock (Hand) regular": "\uf259",
	"Scissors (Hand) solid": "\uf257",
	"Scissors (Hand) regular": "\uf257",
	"Rock (Hand) solid": "\uf255",
	"Rock (Hand) regular": "\uf255",
	"Pointer (Hand) solid": "\uf25a",
	"Pointer (Hand) regular": "\uf25a",
	"Hand Pointing Up solid": "\uf0a6",
	"Hand Pointing Up regular": "\uf0a6",
	"Hand Pointing Right solid": "\uf0a4",
	"Hand Pointing Right regular": "\uf0a4",
	"Hand Pointing Left solid": "\uf0a5",
	"Hand Pointing Left regular": "\uf0a5",
	"Hand Pointing Down solid": "\uf0a7",
	"Hand Pointing Down regular": "\uf0a7",
	"Peace (Hand) solid": "\uf25b",
	"Peace (Hand) regular": "\uf25b",
	"Paper (Hand) solid": "\uf256",
	"Paper (Hand) regular": "\uf256",
	"Lizard (Hand) solid": "\uf258",
	"Lizard (Hand) regular": "\uf258",
	"Hand Holding US Dollar solid": "\uf4c0",
	"Hand Holding Heart solid": "\uf4be",
	"Hand Holding solid": "\uf4bd",
	"Hacker News Square brands": "\uf3af",
	"Hacker News brands": "\uf1d4",
	"H Square solid": "\uf0fd",
	"Gulp brands": "\uf3ae",
	"Grunt brands": "\uf3ad",
	"Gripfire, Inc. brands": "\uf3ac",
	"Grav brands": "\uf2d6",
	"Gratipay (Gittip) brands": "\uf184",
	"Graduation Cap solid": "\uf19d",
	"Google Wallet brands": "\uf1ee",
	"Google Plus Square brands": "\uf0d4",
	"Google Plus G brands": "\uf0d5",
	"Google Plus brands": "\uf2b3",
	"Google Play brands": "\uf3ab",
	"Google Drive brands": "\uf3aa",
	"Google Logo brands": "\uf1a0",
	"Goodreads G brands": "\uf3a9",
	"Goodreads brands": "\uf3a8",
	"Golf Ball solid": "\uf450",
	"Gofore brands": "\uf3a7",
	"Globe solid": "\uf0ac",
	"Glide G brands": "\uf2a6",
	"Glide brands": "\uf2a5",
	"Martini Glass solid": "\uf000",
	"Gitter brands": "\uf426",
	"GitLab brands": "\uf296",
	"GitKraken brands": "\uf3a6",
	"GitHub Square brands": "\uf092",
	"Alternate GitHub brands": "\uf113",
	"GitHub brands": "\uf09b",
	"Git Square brands": "\uf1d2",
	"Git brands": "\uf1d3",
	"gift solid": "\uf06b",
	"GG Currency Circle brands": "\uf261",
	"GG Currency brands": "\uf260",
	"Get Pocket brands": "\uf265",
	"Genderless solid": "\uf22d",
	"Gem solid": "\uf3a5",
	"Gem regular": "\uf3a5",
	"Gavel solid": "\uf0e3",
	"Gamepad solid": "\uf11b",
	"Galactic Senate brands": "\uf50d",
	"Galactic Republic brands": "\uf50c",
	"Futbol solid": "\uf1e3",
	"Futbol regular": "\uf1e3",
	"Fulcrum brands": "\uf50b",
	"Frown solid": "\uf119",
	"Frown regular": "\uf119",
	"FreeBSD brands": "\uf3a4",
	"Free Code Camp brands": "\uf2c5",
	"Foursquare brands": "\uf180",
	"forward solid": "\uf04e",
	"Forumbee brands": "\uf211",
	"Alternate Fort Awesome brands": "\uf3a3",
	"Fort Awesome brands": "\uf286",
	"Football Ball solid": "\uf44e",
	"Fonticons Fi brands": "\uf3a2",
	"Fonticons brands": "\uf280",
	"Font Awesome Full Logo regular": "\uf4e6",
	"Font Awesome Full Logo solid": "\uf4e6",
	"Font Awesome Full Logo brands": "\uf4e6",
	"Font Awesome Flag brands": "\uf425",
	"Alternate Font Awesome brands": "\uf35c",
	"Font Awesome brands": "\uf2b4",
	"font solid": "\uf031",
	"Folder Open solid": "\uf07c",
	"Folder Open regular": "\uf07c",
	"Folder solid": "\uf07b",
	"Folder regular": "\uf07b",
	"Fly brands": "\uf417",
	"Flipboard brands": "\uf44d",
	"Flickr brands": "\uf16e",
	"Flask solid": "\uf0c3",
	"flag-checkered solid": "\uf11e",
	"flag solid": "\uf024",
	"flag regular": "\uf024",
	"firstdraft brands": "\uf3a1",
	"Alternate First Order brands": "\uf50a",
	"First Order brands": "\uf2b0",
	"First Aid solid": "\uf479",
	"Firefox brands": "\uf269",
	"fire-extinguisher solid": "\uf134",
	"fire solid": "\uf06d",
	"Filter solid": "\uf0b0",
	"Film solid": "\uf008",
	"Word File solid": "\uf1c2",
	"Word File regular": "\uf1c2",
	"Video File solid": "\uf1c8",
	"Video File regular": "\uf1c8",
	"Powerpoint File solid": "\uf1c4",
	"Powerpoint File regular": "\uf1c4",
	"PDF File solid": "\uf1c1",
	"PDF File regular": "\uf1c1",
	"Medical File Alternate solid": "\uf478",
	"Medical File solid": "\uf477",
	"Image File solid": "\uf1c5",
	"Image File regular": "\uf1c5",
	"Excel File solid": "\uf1c3",
	"Excel File regular": "\uf1c3",
	"Code File solid": "\uf1c9",
	"Code File regular": "\uf1c9",
	"Audio File solid": "\uf1c7",
	"Audio File regular": "\uf1c7",
	"Archive File solid": "\uf1c6",
	"Archive File regular": "\uf1c6",
	"Alternate File solid": "\uf15c",
	"Alternate File regular": "\uf15c",
	"File solid": "\uf15b",
	"File regular": "\uf15b",
	"fighter-jet solid": "\uf0fb",
	"Female solid": "\uf182",
	"Fax solid": "\uf1ac",
	"fast-forward solid": "\uf050",
	"fast-backward solid": "\uf049",
	"Facebook Square brands": "\uf082",
	"Facebook Messenger brands": "\uf39f",
	"Facebook F brands": "\uf39e",
	"Facebook brands": "\uf09a",
	"Eye Slash solid": "\uf070",
	"Eye Slash regular": "\uf070",
	"Eye Dropper solid": "\uf1fb",
	"Eye solid": "\uf06e",
	"Eye regular": "\uf06e",
	"Alternate External Link Square solid": "\uf360",
	"Alternate External Link solid": "\uf35d",
	"ExpeditedSSL brands": "\uf23e",
	"Alternate Expand Arrows solid": "\uf31e",
	"Expand solid": "\uf065",
	"Exclamation Triangle solid": "\uf071",
	"Exclamation Circle solid": "\uf06a",
	"exclamation solid": "\uf12a",
	"Alternate Exchange solid": "\uf362",
	"Euro Sign solid": "\uf153",
	"Etsy brands": "\uf2d7",
	"Ethereum brands": "\uf42e",
	"Erlang brands": "\uf39d",
	"eraser solid": "\uf12d",
	"Envira Gallery brands": "\uf299",
	"Envelope Square solid": "\uf199",
	"Envelope Open solid": "\uf2b6",
	"Envelope Open regular": "\uf2b6",
	"Envelope solid": "\uf0e0",
	"Envelope regular": "\uf0e0",
	"Galactic Empire brands": "\uf1d1",
	"Ember brands": "\uf423",
	"Vertical Ellipsis solid": "\uf142",
	"Horizontal Ellipsis solid": "\uf141",
	"Elementor brands": "\uf430",
	"eject solid": "\uf052",
	"Edit solid": "\uf044",
	"Edit regular": "\uf044",
	"Edge Browser brands": "\uf282",
	"eBay brands": "\uf4f4",
	"Earlybirds brands": "\uf39a",
	"Dyalog brands": "\uf399",
	"Drupal Logo brands": "\uf1a9",
	"Dropbox brands": "\uf16b",
	"Dribbble Square brands": "\uf397",
	"Dribbble brands": "\uf17d",
	"Draft2digital brands": "\uf396",
	"Download solid": "\uf019",
	"Dove solid": "\uf4ba",
	"Dot Circle solid": "\uf192",
	"Dot Circle regular": "\uf192",
	"Donate solid": "\uf4b9",
	"Dolly Flatbed solid": "\uf474",
	"Dolly solid": "\uf472",
	"Dollar Sign solid": "\uf155",
	"Docker brands": "\uf395",
	"DocHub brands": "\uf394",
	"DNA solid": "\uf471",
	"Discourse brands": "\uf393",
	"Discord brands": "\uf392",
	"Digital Ocean brands": "\uf391",
	"Digg Logo brands": "\uf1a6",
	"Diagnoses solid": "\uf470",
	"deviantART brands": "\uf1bd",
	"Desktop solid": "\uf108",
	"Deskpro brands": "\uf38f",
	"deploy.dog brands": "\uf38e",
	"Delicious Logo brands": "\uf1a5",
	"Deaf solid": "\uf2a4",
	"Database solid": "\uf1c0",
	"DashCube brands": "\uf210",
	"Dungeons & Dragons brands": "\uf38d",
	"Cuttlefish brands": "\uf38c",
	"Cut solid": "\uf0c4",
	"Cubes solid": "\uf1b3",
	"Cube solid": "\uf1b2",
	"Alternate CSS3 Logo brands": "\uf38b",
	"CSS 3 Logo brands": "\uf13c",
	"Crosshairs solid": "\uf05b",
	"crop solid": "\uf125",
	"Credit Card solid": "\uf09d",
	"Credit Card regular": "\uf09d",
	"Creative Commons Share brands": "\uf4f2",
	"Creative Commons Sampling + brands": "\uf4f1",
	"Creative Commons Sampling brands": "\uf4f0",
	"Creative Commons Share Alike brands": "\uf4ef",
	"Creative Commons Remix brands": "\uf4ee",
	"Creative Commons Public Domain Alternate brands": "\uf4ed",
	"Creative Commons Public Domain brands": "\uf4ec",
	"Creative Commons No Derivative Works brands": "\uf4eb",
	"Creative Commons Noncommercial (Yen Sign) brands": "\uf4ea",
	"Creative Commons Noncommercial (Euro Sign) brands": "\uf4e9",
	"Creative Commons Noncommercial brands": "\uf4e8",
	"Creative Commons Attribution brands": "\uf4e7",
	"Creative Commons brands": "\uf25e",
	"cPanel brands": "\uf388",
	"Couch solid": "\uf4b8",
	"Copyright solid": "\uf1f9",
	"Copyright regular": "\uf1f9",
	"Copy solid": "\uf0c5",
	"Copy regular": "\uf0c5",
	"Contao brands": "\uf26d",
	"Connect Develop brands": "\uf20e",
	"Compress solid": "\uf066",
	"Compass solid": "\uf14e",
	"Compass regular": "\uf14e",
	"comments solid": "\uf086",
	"comments regular": "\uf086",
	"Comment Slash solid": "\uf4b3",
	"Comment Dots solid": "\uf4ad",
	"Comment Dots regular": "\uf4ad",
	"Alternate Comment solid": "\uf27a",
	"Alternate Comment regular": "\uf27a",
	"comment solid": "\uf075",
	"comment regular": "\uf075",
	"Columns solid": "\uf0db",
	"cogs solid": "\uf085",
	"cog solid": "\uf013",
	"Coffee solid": "\uf0f4",
	"Codie Pie brands": "\uf284",
	"Codepen brands": "\uf1cb",
	"Code Branch solid": "\uf126",
	"Code solid": "\uf121",
	"cloudversify brands": "\uf385",
	"Cloudsmith brands": "\uf384",
	"cloudscale.ch brands": "\uf383",
	"Cloud Upload Alternate solid": "\uf382",
	"Cloud Download Alternate solid": "\uf381",
	"Cloud solid": "\uf0c2",
	"Closed Captioning solid": "\uf20a",
	"Closed Captioning regular": "\uf20a",
	"Clone solid": "\uf24d",
	"Clone regular": "\uf24d",
	"Clock solid": "\uf017",
	"Clock regular": "\uf017",
	"Clipboard List solid": "\uf46d",
	"Clipboard Check solid": "\uf46c",
	"Clipboard solid": "\uf328",
	"Clipboard regular": "\uf328",
	"Circle Notched solid": "\uf1ce",
	"Circle solid": "\uf111",
	"Circle regular": "\uf111",
	"Chrome brands": "\uf268",
	"Child solid": "\uf1ae",
	"chevron-up solid": "\uf077",
	"chevron-right solid": "\uf054",
	"chevron-left solid": "\uf053",
	"chevron-down solid": "\uf078",
	"Chevron Circle Up solid": "\uf139",
	"Chevron Circle Right solid": "\uf138",
	"Chevron Circle Left solid": "\uf137",
	"Chevron Circle Down solid": "\uf13a",
	"Chess Rook solid": "\uf447",
	"Chess Queen solid": "\uf445",
	"Chess Pawn solid": "\uf443",
	"Chess Knight solid": "\uf441",
	"Chess King solid": "\uf43f",
	"Chess Board solid": "\uf43c",
	"Chess Bishop solid": "\uf43a",
	"Chess solid": "\uf439",
	"Check Square solid": "\uf14a",
	"Check Square regular": "\uf14a",
	"Check Circle solid": "\uf058",
	"Check Circle regular": "\uf058",
	"Check solid": "\uf00c",
	"Pie Chart solid": "\uf200",
	"Line Chart solid": "\uf201",
	"Bar Chart solid": "\uf080",
	"Bar Chart regular": "\uf080",
	"Area Chart solid": "\uf1fe",
	"certificate solid": "\uf0a3",
	"Centercode brands": "\uf380",
	"Visa Credit Card brands": "\uf1f0",
	"Stripe Credit Card brands": "\uf1f5",
	"Paypal Credit Card brands": "\uf1f4",
	"MasterCard Credit Card brands": "\uf1f1",
	"JCB Credit Card brands": "\uf24b",
	"Discover Credit Card brands": "\uf1f2",
	"Diner's Club Credit Card brands": "\uf24c",
	"Apple Pay Credit Card brands": "\uf416",
	"American Express Credit Card brands": "\uf1f3",
	"Amazon Pay Credit Card brands": "\uf42d",
	"Add to Shopping Cart solid": "\uf217",
	"Shopping Cart Arrow Down solid": "\uf218",
	"Caret Up solid": "\uf0d8",
	"Caret Square Up solid": "\uf151",
	"Caret Square Up regular": "\uf151",
	"Caret Square Right solid": "\uf152",
	"Caret Square Right regular": "\uf152",
	"Caret Square Left solid": "\uf191",
	"Caret Square Left regular": "\uf191",
	"Caret Square Down solid": "\uf150",
	"Caret Square Down regular": "\uf150",
	"Caret Right solid": "\uf0da",
	"Caret Left solid": "\uf0d9",
	"Caret Down solid": "\uf0d7",
	"Car solid": "\uf1b9",
	"Capsules solid": "\uf46b",
	"Retro Camera solid": "\uf083",
	"camera solid": "\uf030",
	"Calendar Times solid": "\uf273",
	"Calendar Times regular": "\uf273",
	"Calendar Plus solid": "\uf271",
	"Calendar Plus regular": "\uf271",
	"Calendar Minus solid": "\uf272",
	"Calendar Minus regular": "\uf272",
	"Calendar Check solid": "\uf274",
	"Calendar Check regular": "\uf274",
	"Alternate Calendar solid": "\uf073",
	"Alternate Calendar regular": "\uf073",
	"Calendar solid": "\uf133",
	"Calendar regular": "\uf133",
	"Calculator solid": "\uf1ec",
	"BuySellAds brands": "\uf20d",
	"Bus solid": "\uf207"
} as const;